logging:
  level:
    root: DEBUG
spring:
  
  application:
    
    name: spring-rag-demo
  datasource:
    url: jdbc:postgresql://${DB_HOST:pgvector}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:devcontainer}
    driver-class-name: org.postgresql.Driver
  ai:
    # google.genai: 
    #   api-key: ${GOOGLE_GENAI_API_KEY}
    #   project-id: ${GOOGLE_CLOUD_PROJECT_ID}
    #   chat.options.model: models/gemini-2.5-flash-lite
    #   embedding.api-key: ${GOOGLE_GENAI_API_KEY}
    vectorstore:
      pgvector:
        initialize-schema: true
        # HNSW is limited to 2000 dims; use IVFFLAT when embedding size is larger
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        #dimensions: 768
        # Drop/recreate the table on startup so schema matches the dimensions/index above
        remove-existing-vector-store-table: true
    ollama:
      base-url: ${OLLAMA_API_BASE_URL:http://host.docker.internal:11434}
      chat:
        model: llama3.1
      embedding:
        model: nomic-embed-text
      init.timeout: 60000
rag:
    top-k: 5
    similarity-threshold: 0.3
    classpath-file: "Test.pdf"