networks:
  appnet:
services:
  devcontainer:
    env_file:
      - .env.local
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - pgvector
    

  pgvector:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_DB: rag_demo
      POSTGRES_PASSWORD: devcontainer
    volumes:
      - spring-rag-demo-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  spring-rag-demo-db: